version: '3.7'

services:
  whiskers-backend:
    build:
      context: ./
      target: production-build-stage
      dockerfile: Dockerfile
    container_name: whiskers
    ports:
      - '80:80'
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: 'always'
    networks:
      - backend

networks:
  backend:
    driver: bridge
